### ISSUE TITLE
Jest E2E would not exit

### ISSUE THREAD

**Issue by nerdDan** [nestjs-community/nestjs-amqp#18]
I am writing an E2E test for my app which imports `nestjs-amqp`. The test would not exit after all the test cases finished. I guess it is the AMQP connection was not closed. If it is, should I close it manually or should `nestjs-amqp` close it automatically through something like `OnModuleDestroy`?

https://github.com/nestjs/nest/issues/899

**Comment by bashleigh** [comment]
Yea, in my tests I get the connection and [close it](https://github.com/nestjs-community/nestjs-amqp/blob/master/src/__tests__/amqp.module.spec.ts#L25).  I didn't think of adding a onModuleDestroy. You can make a PR if you want to? Or I don't mind doing it? I might have to do it tomorrow though? Would also need to be able to get all configured providers by their token which might be an issue? Unless we make a provider with a value of all the provider names that we've created?

**Comment by bashleigh** [comment]
Got bored: started on it already :joy: just going to see what travis thinks of the new implementation then I shall remove from the tests and see what it thinks of that then we're all good 👍

**Comment by bashleigh** [comment]
Seems like it's still hanging, think I might have to reimplement the tests in order for them to pass. I'll do this when I can! But it looks possible!

**Comment by nerdDan** [comment]
Thank you :heart:

**Comment by bashleigh** [comment]
Thanks for bringing it up!

**Comment by bashleigh** [comment]
Ok so,  I've merged that branch and I'll release as `v0.1.1`. I've also added a new issue to refactor the tests at a later date. I'm keeping this issue until @nerdDan can give me some feedback on how `v0.1.1` preforms with what you're trying to do.

**Comment by nerdDan** [comment]
I am in a frustrating situation. After upgrading `nestjs-amqp`,  my E2E test is giving uncertain results. Sometimes it exits without error; sometimes it hangs after all `it`s finish; sometimes it says there were an unhandled promise rejection.

I am feeling it is my code causing errors. So I am closing this issue and will feedback my further discoveries.

**Comment by bashleigh** [comment]
ok, it's cool. Feel free to ad your test code here and I'll have a look at it

**Comment by nerdDan** [comment]
Test still hangs. It looks like resulting from `@nestjs/typeorm`. https://github.com/nestjs/typeorm/issues/50

`nestjs-amqp` is all good so far. Thank you!
